// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace
{
    public static partial class ObjectExtensions
    {
        public static ISessionContext SessionContext(this IStrategy @this) => @this.Session.Context();

        public static WorkspaceContext WorkspaceContext(this IStrategy @this) => @this.Session.Workspace.Context();
    }

    public static partial class SessionExtensions
    {
        public static ISessionContext Context(this ISession @this) => ((ISessionContext)@this.SessionLifecycle);
    }

    public static partial class WorkspaceExtensions
    {
        public static WorkspaceContext Context(this IWorkspace @this) => ((WorkspaceContext)@this.StateLifecycle);
    }
}
