module.exports = {
  projects: [
    '<rootDir>/apps/react',
    '<rootDir>/libs/data/system',
    '<rootDir>/libs/domain/custom',
    '<rootDir>/libs/domain/generated',
    '<rootDir>/libs/meta/generated',
    '<rootDir>/libs/meta/system',
    '<rootDir>/libs/protocol/system',
    '<rootDir>/libs/workspace/memory',
    '<rootDir>/libs/workspace/system',
    '<rootDir>/libs/workspace/tests',
    '<rootDir>/libs/client/tests',
    '<rootDir>/libs/client/fetch',
    '<rootDir>/libs/meta/tests',
    '<rootDir>/libs/data/core',
    '<rootDir>/libs/meta/core',
    '<rootDir>/libs/protocol/core',
    '<rootDir>/libs/workspace/core',
  ],
};
