// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Database
{
    public static partial class ObjectExtensions
    {
        public static ISessionContext SessionContext(this IObject @this) => @this.Strategy.Session.Context();

        public static IDatabaseContext DatabaseContext(this IObject @this) => @this.Strategy.Session.Database.Context();
    }

    public static partial class SessionExtensions
    {
        public static ISessionContext Context(this ISession @this) => ((ISessionContext)@this.StateLifecycle);
    }

    public static partial class DatabaseExtensions
    {
        public static IDatabaseContext Context(this IDatabase @this) => ((IDatabaseContext)@this.StateLifecycle);
    }
}
