// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors
{
    public static partial class ObjectsExtensions
    {
        public static ISessionInstance SessionState(this IObjects @this)
        {
            return @this.Session.State();
        }

        public static IDatabaseInstance DatabaseState(this IObjects @this)
        {
            return @this.Session.Database.State();
        }
    }
    
    public static partial class ObjectExtensions
    {
        public static ISessionInstance SessionState(this IObject @this)
        {
            return @this.Strategy.Session.State();
        }

        public static IDatabaseInstance DatabaseState(this IObject @this)
        {
            return @this.Strategy.Session.Database.State();
        }
     }

    public static partial class SessionExtensions
    {
        public static ISessionInstance State(this ISession @this)
        {
            return ((ISessionInstance)@this.InstanceLifecycle);
        }
    }

    public static partial class DatabaseExtensions
    {
        public static IDatabaseInstance State(this IDatabase @this)
        {
            return ((IDatabaseInstance)@this.InstanceLifecycle);
        }
    }
}
