// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace
{
    public static partial class ObjectExtensions
    {
        public static ISessionScope SessionScope(this ISessionObject @this)
        {
            return @this.Session.Scope();
        }

        public static WorkspaceScope WorkspaceScope(this ISessionObject @this)
        {
            return @this.Session.Workspace.Scope();
        }
     }

    public static partial class SessionExtensions
    {
        public static ISessionScope Scope(this ISession @this)
        {
            return ((ISessionScope)@this.Lifecycle);
        }
    }

    public static partial class WorkspaceExtensions
    {
        public static WorkspaceScope Scope(this IWorkspace @this)
        {
            return ((WorkspaceScope)@this.Lifecycle);
        }
    }
}
