// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace
{
    public static partial class ObjectExtensions
    {
        public static ISessionState SessionScope(this ISessionObject @this)
        {
            return @this.Session.Scope();
        }

        public static WorkspaceState WorkspaceScope(this ISessionObject @this)
        {
            return @this.Session.Workspace.Scope();
        }
     }

    public static partial class SessionExtensions
    {
        public static ISessionState Scope(this ISession @this)
        {
            return ((ISessionState)@this.Lifecycle);
        }
    }

    public static partial class WorkspaceExtensions
    {
        public static WorkspaceState Scope(this IWorkspace @this)
        {
            return ((WorkspaceState)@this.Lifecycle);
        }
    }
}
