module.exports = {
  projects: [
    ,
    '<rootDir>/libs/workspace/adapters/json/system',
    '<rootDir>/libs/workspace/domain/core',
    '<rootDir>/libs/workspace/meta/core',
    '<rootDir>/libs/workspace/meta/lazy/system',
    '<rootDir>/libs/workspace/meta/lazy/system-tests',
    '<rootDir>/libs/protocol/json/system',
    '<rootDir>/libs/workspace/meta/system',
    '<rootDir>/libs/workspace/domain/system',
    '<rootDir>/libs/workspace/adapters/system',
    '<rootDir>/libs/workspace/adapters/json/system-tests',
    '<rootDir>/libs/workspace/angular/base',
    '<rootDir>/apps/angular/base/app',
    '<rootDir>/libs/workspace/domain/base',
    '<rootDir>/libs/workspace/meta/base',
    '<rootDir>/libs/workspace/meta/json/base',
  ],
};
