trigger:
- master
- feature/*
- issue/*

stages:
- stage: Platform
  jobs:
  - job: Test
    timeoutInMinutes: 180

    pool:
      vmImage: 'windows-2019'

    strategy:
      matrix:
        adapters_memory:
          target: 'AdaptersTestMemory'
        adapters_sqlclient:
          target: 'AdaptersTestSqlClient'
        adapters_npgsql:
          target: 'AdaptersTestNpgsql'
        core_database:
          target: 'CoreDatabaseTest'
        core_workspace:
          target: 'CoreWorkspaceTest'
        base_workspace_typescript:
          target: 'BaseWorkspaceTest'

    steps:
    - powershell: Set-Culture -CultureInfo nl-BE
      displayName: CultureInfo nl-BE
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1 sdk'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: -target install
        failOnStderr: true
      displayName: Install
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: -target $(target)
        failOnStderr: true
      displayName: Running $(target)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testRunTitle: $(target)
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: 'artifacts/tests'
      displayName: 'Results for $(target)'
