trigger:
- master
- feature/*
- issue/*

stages:
- stage: System
  jobs:
  - job: Test
    timeoutInMinutes: 120

    pool:
      vmImage: 'windows-2019'

    strategy:
      matrix:
        adapters_memory:
          target: 'CiAdaptersTestMemory'
        adapters_sqlclient:
          target: 'CiAdaptersTestSqlClient'
        adapters_npgsql:
          target: 'CiAdaptersTestNpgsql'
        core_database:
          target: 'CiCoreDatabaseTest'
        core_workspace:
          target: 'CiCoreWorkspaceTest'
        apps_database:
          target: 'CiAppsDatabaseTest'
        demos:
          target: 'CiDemosTest'

    steps:
    - powershell: Set-Culture -CultureInfo nl-BE
      displayName: CultureInfo nl-BE
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1 sdk'
      inputs:
        packageType: sdk
        version: 3.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: -target $(target)
        failOnStderr: true
      displayName: Running $(target)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testRunTitle: $(target)
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: 'artifacts/tests'
      displayName: 'Results for $(target)'
