// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace.Domain
{
    using System.Linq;

	public partial class WorkspaceC1 
	{
        public override string ToString() => $"{this.Strategy.Class.SingularName}:{this.Strategy.Id}";
    }
}
