// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Database.Domain
{
    using Domain;

    public static partial class ObjectsExtensions
    {
        public static ITransactionContext TransactionContext(this IObjects @this) => @this.Transaction.Context();

        public static IDatabaseContext DatabaseContext(this IObjects @this) => @this.Transaction.Database.Context();
    }

    public static partial class ObjectExtensions
    {
        public static ITransactionContext TransactionContext(this IObject @this) => @this.Strategy.Transaction.Context();

        public static IDatabaseContext DatabaseContext(this IObject @this) => @this.Strategy.Transaction.Database.Context();
    }

    public static partial class TransactionExtensions
    {
        public static ITransactionContext Context(this ITransaction @this) => ((ITransactionContext)@this.Lifecycle);
    }

    public static partial class DatabaseExtensions
    {
        public static IDatabaseContext Context(this IDatabase @this) => ((IDatabaseContext)@this.Lifecycle);
    }
}
