@startuml overview

' Database
'---------
interface Database {
    +metaPopulation
    +constructorByObjectType
    +accessControlById
}
Database *-- DatabaseObject

interface DatabaseObject {
    +id
    +objectType
    +version
    +roleByRoleTypeId
}

' Workspace
'---------
interface Workspace {
}
Workspace --> Database
Workspace *-- WorkspaceObject

interface WorkspaceObject {
    +id
    +objectType
    +version
}
WorkspaceObject --> DatabaseObject

' Session
'---------
interface Session {
    +hasChanges
}
Session --> Workspace
Session *-- SessionObject

interface SessionObject {
    +id
    +objectType
    +newId
    +version
    +isNew
    +hasChanges
}
SessionObject --> WorkspaceObject
SessionObject --> DatabaseObject

@enduml
