//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Integration {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("GeneralLedgerAccounts")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class GeneralLedgerAccounts : global::System.Data.DataSet {
        
        private GeneralLedgerAccountDataTable tableGeneralLedgerAccount;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public GeneralLedgerAccounts() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected GeneralLedgerAccounts(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GeneralLedgerAccount"] != null)) {
                    base.Tables.Add(new GeneralLedgerAccountDataTable(ds.Tables["GeneralLedgerAccount"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GeneralLedgerAccountDataTable GeneralLedgerAccount {
            get {
                return this.tableGeneralLedgerAccount;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            GeneralLedgerAccounts cln = ((GeneralLedgerAccounts)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GeneralLedgerAccount"] != null)) {
                    base.Tables.Add(new GeneralLedgerAccountDataTable(ds.Tables["GeneralLedgerAccount"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableGeneralLedgerAccount = ((GeneralLedgerAccountDataTable)(base.Tables["GeneralLedgerAccount"]));
            if ((initTable == true)) {
                if ((this.tableGeneralLedgerAccount != null)) {
                    this.tableGeneralLedgerAccount.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "GeneralLedgerAccounts";
            this.Prefix = "";
            this.Locale = new global::System.Globalization.CultureInfo("en-US");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGeneralLedgerAccount = new GeneralLedgerAccountDataTable();
            base.Tables.Add(this.tableGeneralLedgerAccount);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeGeneralLedgerAccount() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            GeneralLedgerAccounts ds = new GeneralLedgerAccounts();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void GeneralLedgerAccountRowChangeEventHandler(object sender, GeneralLedgerAccountRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GeneralLedgerAccountDataTable : global::System.Data.TypedTableBase<GeneralLedgerAccountRow> {
            
            private global::System.Data.DataColumn columnReferenceCode;
            
            private global::System.Data.DataColumn columnCounterPartAccount;
            
            private global::System.Data.DataColumn columnSortCode;
            
            private global::System.Data.DataColumn columnReferenceNumber;
            
            private global::System.Data.DataColumn columnName;
            
            private global::System.Data.DataColumn columnDescription;
            
            private global::System.Data.DataColumn columnBalanceSide;
            
            private global::System.Data.DataColumn columnLevel;
            
            private global::System.Data.DataColumn columnIsRgsExcluded;
            
            private global::System.Data.DataColumn columnIsRgsBase;
            
            private global::System.Data.DataColumn columnIsRgsExtended;
            
            private global::System.Data.DataColumn columnIsRgsUseWithEZ;
            
            private global::System.Data.DataColumn columnIsRgsUseWithZzp;
            
            private global::System.Data.DataColumn columnIsRgsUseWithWoco;
            
            private global::System.Data.DataColumn columnExcludeRgsBB;
            
            private global::System.Data.DataColumn columnExcludeRgsAgro;
            
            private global::System.Data.DataColumn columnExcludeRgsWKR;
            
            private global::System.Data.DataColumn columnExcludeRgsEZVOF;
            
            private global::System.Data.DataColumn columnExcludeRgsBV;
            
            private global::System.Data.DataColumn columnExcludeRgsWoco;
            
            private global::System.Data.DataColumn columnExcludeRgsBank;
            
            private global::System.Data.DataColumn columnExcludeRgsOZW;
            
            private global::System.Data.DataColumn columnExcludeRgsAfrekSyst;
            
            private global::System.Data.DataColumn columnExcludeRgsNivo5;
            
            private global::System.Data.DataColumn columnExcludeRgsUitbr5;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public GeneralLedgerAccountDataTable() {
                this.TableName = "GeneralLedgerAccount";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal GeneralLedgerAccountDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected GeneralLedgerAccountDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ReferenceCodeColumn {
                get {
                    return this.columnReferenceCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CounterPartAccountColumn {
                get {
                    return this.columnCounterPartAccount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SortCodeColumn {
                get {
                    return this.columnSortCode;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ReferenceNumberColumn {
                get {
                    return this.columnReferenceNumber;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NameColumn {
                get {
                    return this.columnName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DescriptionColumn {
                get {
                    return this.columnDescription;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn BalanceSideColumn {
                get {
                    return this.columnBalanceSide;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LevelColumn {
                get {
                    return this.columnLevel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IsRgsExcludedColumn {
                get {
                    return this.columnIsRgsExcluded;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IsRgsBaseColumn {
                get {
                    return this.columnIsRgsBase;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IsRgsExtendedColumn {
                get {
                    return this.columnIsRgsExtended;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IsRgsUseWithEZColumn {
                get {
                    return this.columnIsRgsUseWithEZ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IsRgsUseWithZzpColumn {
                get {
                    return this.columnIsRgsUseWithZzp;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IsRgsUseWithWocoColumn {
                get {
                    return this.columnIsRgsUseWithWoco;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsBBColumn {
                get {
                    return this.columnExcludeRgsBB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsAgroColumn {
                get {
                    return this.columnExcludeRgsAgro;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsWKRColumn {
                get {
                    return this.columnExcludeRgsWKR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsEZVOFColumn {
                get {
                    return this.columnExcludeRgsEZVOF;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsBVColumn {
                get {
                    return this.columnExcludeRgsBV;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsWocoColumn {
                get {
                    return this.columnExcludeRgsWoco;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsBankColumn {
                get {
                    return this.columnExcludeRgsBank;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsOZWColumn {
                get {
                    return this.columnExcludeRgsOZW;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsAfrekSystColumn {
                get {
                    return this.columnExcludeRgsAfrekSyst;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsNivo5Column {
                get {
                    return this.columnExcludeRgsNivo5;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExcludeRgsUitbr5Column {
                get {
                    return this.columnExcludeRgsUitbr5;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public GeneralLedgerAccountRow this[int index] {
                get {
                    return ((GeneralLedgerAccountRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event GeneralLedgerAccountRowChangeEventHandler GeneralLedgerAccountRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event GeneralLedgerAccountRowChangeEventHandler GeneralLedgerAccountRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event GeneralLedgerAccountRowChangeEventHandler GeneralLedgerAccountRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event GeneralLedgerAccountRowChangeEventHandler GeneralLedgerAccountRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddGeneralLedgerAccountRow(GeneralLedgerAccountRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public GeneralLedgerAccountRow AddGeneralLedgerAccountRow(
                        string ReferenceCode, 
                        string CounterPartAccount, 
                        string SortCode, 
                        string ReferenceNumber, 
                        string Name, 
                        string Description, 
                        string BalanceSide, 
                        long Level, 
                        bool IsRgsExcluded, 
                        bool IsRgsBase, 
                        bool IsRgsExtended, 
                        bool IsRgsUseWithEZ, 
                        bool IsRgsUseWithZzp, 
                        bool IsRgsUseWithWoco, 
                        bool ExcludeRgsBB, 
                        bool ExcludeRgsAgro, 
                        bool ExcludeRgsWKR, 
                        bool ExcludeRgsEZVOF, 
                        bool ExcludeRgsBV, 
                        bool ExcludeRgsWoco, 
                        bool ExcludeRgsBank, 
                        bool ExcludeRgsOZW, 
                        bool ExcludeRgsAfrekSyst, 
                        bool ExcludeRgsNivo5, 
                        bool ExcludeRgsUitbr5) {
                GeneralLedgerAccountRow rowGeneralLedgerAccountRow = ((GeneralLedgerAccountRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ReferenceCode,
                        CounterPartAccount,
                        SortCode,
                        ReferenceNumber,
                        Name,
                        Description,
                        BalanceSide,
                        Level,
                        IsRgsExcluded,
                        IsRgsBase,
                        IsRgsExtended,
                        IsRgsUseWithEZ,
                        IsRgsUseWithZzp,
                        IsRgsUseWithWoco,
                        ExcludeRgsBB,
                        ExcludeRgsAgro,
                        ExcludeRgsWKR,
                        ExcludeRgsEZVOF,
                        ExcludeRgsBV,
                        ExcludeRgsWoco,
                        ExcludeRgsBank,
                        ExcludeRgsOZW,
                        ExcludeRgsAfrekSyst,
                        ExcludeRgsNivo5,
                        ExcludeRgsUitbr5};
                rowGeneralLedgerAccountRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowGeneralLedgerAccountRow);
                return rowGeneralLedgerAccountRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                GeneralLedgerAccountDataTable cln = ((GeneralLedgerAccountDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GeneralLedgerAccountDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnReferenceCode = base.Columns["ReferenceCode"];
                this.columnCounterPartAccount = base.Columns["CounterPartAccount"];
                this.columnSortCode = base.Columns["SortCode"];
                this.columnReferenceNumber = base.Columns["ReferenceNumber"];
                this.columnName = base.Columns["Name"];
                this.columnDescription = base.Columns["Description"];
                this.columnBalanceSide = base.Columns["BalanceSide"];
                this.columnLevel = base.Columns["Level"];
                this.columnIsRgsExcluded = base.Columns["IsRgsExcluded"];
                this.columnIsRgsBase = base.Columns["IsRgsBase"];
                this.columnIsRgsExtended = base.Columns["IsRgsExtended"];
                this.columnIsRgsUseWithEZ = base.Columns["IsRgsUseWithEZ"];
                this.columnIsRgsUseWithZzp = base.Columns["IsRgsUseWithZzp"];
                this.columnIsRgsUseWithWoco = base.Columns["IsRgsUseWithWoco"];
                this.columnExcludeRgsBB = base.Columns["ExcludeRgsBB"];
                this.columnExcludeRgsAgro = base.Columns["ExcludeRgsAgro"];
                this.columnExcludeRgsWKR = base.Columns["ExcludeRgsWKR"];
                this.columnExcludeRgsEZVOF = base.Columns["ExcludeRgsEZVOF"];
                this.columnExcludeRgsBV = base.Columns["ExcludeRgsBV"];
                this.columnExcludeRgsWoco = base.Columns["ExcludeRgsWoco"];
                this.columnExcludeRgsBank = base.Columns["ExcludeRgsBank"];
                this.columnExcludeRgsOZW = base.Columns["ExcludeRgsOZW"];
                this.columnExcludeRgsAfrekSyst = base.Columns["ExcludeRgsAfrekSyst"];
                this.columnExcludeRgsNivo5 = base.Columns["ExcludeRgsNivo5"];
                this.columnExcludeRgsUitbr5 = base.Columns["ExcludeRgsUitbr5"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnReferenceCode = new global::System.Data.DataColumn("ReferenceCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReferenceCode);
                this.columnCounterPartAccount = new global::System.Data.DataColumn("CounterPartAccount", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCounterPartAccount);
                this.columnSortCode = new global::System.Data.DataColumn("SortCode", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSortCode);
                this.columnReferenceNumber = new global::System.Data.DataColumn("ReferenceNumber", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReferenceNumber);
                this.columnName = new global::System.Data.DataColumn("Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnName);
                this.columnDescription = new global::System.Data.DataColumn("Description", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescription);
                this.columnBalanceSide = new global::System.Data.DataColumn("BalanceSide", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBalanceSide);
                this.columnLevel = new global::System.Data.DataColumn("Level", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLevel);
                this.columnIsRgsExcluded = new global::System.Data.DataColumn("IsRgsExcluded", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIsRgsExcluded);
                this.columnIsRgsBase = new global::System.Data.DataColumn("IsRgsBase", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIsRgsBase);
                this.columnIsRgsExtended = new global::System.Data.DataColumn("IsRgsExtended", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIsRgsExtended);
                this.columnIsRgsUseWithEZ = new global::System.Data.DataColumn("IsRgsUseWithEZ", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIsRgsUseWithEZ);
                this.columnIsRgsUseWithZzp = new global::System.Data.DataColumn("IsRgsUseWithZzp", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIsRgsUseWithZzp);
                this.columnIsRgsUseWithWoco = new global::System.Data.DataColumn("IsRgsUseWithWoco", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIsRgsUseWithWoco);
                this.columnExcludeRgsBB = new global::System.Data.DataColumn("ExcludeRgsBB", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsBB);
                this.columnExcludeRgsAgro = new global::System.Data.DataColumn("ExcludeRgsAgro", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsAgro);
                this.columnExcludeRgsWKR = new global::System.Data.DataColumn("ExcludeRgsWKR", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsWKR);
                this.columnExcludeRgsEZVOF = new global::System.Data.DataColumn("ExcludeRgsEZVOF", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsEZVOF);
                this.columnExcludeRgsBV = new global::System.Data.DataColumn("ExcludeRgsBV", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsBV);
                this.columnExcludeRgsWoco = new global::System.Data.DataColumn("ExcludeRgsWoco", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsWoco);
                this.columnExcludeRgsBank = new global::System.Data.DataColumn("ExcludeRgsBank", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsBank);
                this.columnExcludeRgsOZW = new global::System.Data.DataColumn("ExcludeRgsOZW", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsOZW);
                this.columnExcludeRgsAfrekSyst = new global::System.Data.DataColumn("ExcludeRgsAfrekSyst", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsAfrekSyst);
                this.columnExcludeRgsNivo5 = new global::System.Data.DataColumn("ExcludeRgsNivo5", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsNivo5);
                this.columnExcludeRgsUitbr5 = new global::System.Data.DataColumn("ExcludeRgsUitbr5", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExcludeRgsUitbr5);
                this.columnReferenceCode.AllowDBNull = false;
                this.columnCounterPartAccount.AllowDBNull = false;
                this.columnSortCode.AllowDBNull = false;
                this.columnReferenceNumber.AllowDBNull = false;
                this.columnName.AllowDBNull = false;
                this.columnDescription.AllowDBNull = false;
                this.columnBalanceSide.AllowDBNull = false;
                this.columnLevel.AllowDBNull = false;
                this.columnIsRgsExcluded.AllowDBNull = false;
                this.columnIsRgsBase.AllowDBNull = false;
                this.columnIsRgsExtended.AllowDBNull = false;
                this.columnIsRgsUseWithEZ.AllowDBNull = false;
                this.columnIsRgsUseWithZzp.AllowDBNull = false;
                this.columnIsRgsUseWithWoco.AllowDBNull = false;
                this.columnExcludeRgsBB.AllowDBNull = false;
                this.columnExcludeRgsAgro.AllowDBNull = false;
                this.columnExcludeRgsWKR.AllowDBNull = false;
                this.columnExcludeRgsEZVOF.AllowDBNull = false;
                this.columnExcludeRgsBV.AllowDBNull = false;
                this.columnExcludeRgsWoco.AllowDBNull = false;
                this.columnExcludeRgsBank.AllowDBNull = false;
                this.columnExcludeRgsOZW.AllowDBNull = false;
                this.columnExcludeRgsAfrekSyst.AllowDBNull = false;
                this.columnExcludeRgsNivo5.AllowDBNull = false;
                this.columnExcludeRgsUitbr5.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public GeneralLedgerAccountRow NewGeneralLedgerAccountRow() {
                return ((GeneralLedgerAccountRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GeneralLedgerAccountRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(GeneralLedgerAccountRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GeneralLedgerAccountRowChanged != null)) {
                    this.GeneralLedgerAccountRowChanged(this, new GeneralLedgerAccountRowChangeEvent(((GeneralLedgerAccountRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GeneralLedgerAccountRowChanging != null)) {
                    this.GeneralLedgerAccountRowChanging(this, new GeneralLedgerAccountRowChangeEvent(((GeneralLedgerAccountRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GeneralLedgerAccountRowDeleted != null)) {
                    this.GeneralLedgerAccountRowDeleted(this, new GeneralLedgerAccountRowChangeEvent(((GeneralLedgerAccountRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GeneralLedgerAccountRowDeleting != null)) {
                    this.GeneralLedgerAccountRowDeleting(this, new GeneralLedgerAccountRowChangeEvent(((GeneralLedgerAccountRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveGeneralLedgerAccountRow(GeneralLedgerAccountRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                GeneralLedgerAccounts ds = new GeneralLedgerAccounts();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GeneralLedgerAccountDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class GeneralLedgerAccountRow : global::System.Data.DataRow {
            
            private GeneralLedgerAccountDataTable tableGeneralLedgerAccount;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal GeneralLedgerAccountRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGeneralLedgerAccount = ((GeneralLedgerAccountDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ReferenceCode {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.ReferenceCodeColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ReferenceCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CounterPartAccount {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.CounterPartAccountColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.CounterPartAccountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SortCode {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.SortCodeColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.SortCodeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ReferenceNumber {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.ReferenceNumberColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ReferenceNumberColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Name {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.NameColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Description {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.DescriptionColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.DescriptionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string BalanceSide {
                get {
                    return ((string)(this[this.tableGeneralLedgerAccount.BalanceSideColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.BalanceSideColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public long Level {
                get {
                    return ((long)(this[this.tableGeneralLedgerAccount.LevelColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.LevelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRgsExcluded {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.IsRgsExcludedColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.IsRgsExcludedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRgsBase {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.IsRgsBaseColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.IsRgsBaseColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRgsExtended {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.IsRgsExtendedColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.IsRgsExtendedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRgsUseWithEZ {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.IsRgsUseWithEZColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.IsRgsUseWithEZColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRgsUseWithZzp {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.IsRgsUseWithZzpColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.IsRgsUseWithZzpColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRgsUseWithWoco {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.IsRgsUseWithWocoColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.IsRgsUseWithWocoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsBB {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsBBColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsBBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsAgro {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsAgroColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsAgroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsWKR {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsWKRColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsWKRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsEZVOF {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsEZVOFColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsEZVOFColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsBV {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsBVColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsBVColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsWoco {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsWocoColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsWocoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsBank {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsBankColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsBankColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsOZW {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsOZWColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsOZWColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsAfrekSyst {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsAfrekSystColumn]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsAfrekSystColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsNivo5 {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsNivo5Column]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsNivo5Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool ExcludeRgsUitbr5 {
                get {
                    return ((bool)(this[this.tableGeneralLedgerAccount.ExcludeRgsUitbr5Column]));
                }
                set {
                    this[this.tableGeneralLedgerAccount.ExcludeRgsUitbr5Column] = value;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class GeneralLedgerAccountRowChangeEvent : global::System.EventArgs {
            
            private GeneralLedgerAccountRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public GeneralLedgerAccountRowChangeEvent(GeneralLedgerAccountRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public GeneralLedgerAccountRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591