// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Database.Domain
{
    using Domain;

    public static partial class ObjectsExtensions
    {
        public static IDomainTransactionServices TransactionContext(this IObjects @this) => @this.Transaction.Context();

        public static IDomainDatabaseServices DatabaseContext(this IObjects @this) => @this.Transaction.Database.Context();
    }

    public static partial class ObjectExtensions
    {
        public static IDomainTransactionServices TransactionContext(this IObject @this) => @this.Strategy.Transaction.Context();

        public static IDomainDatabaseServices DatabaseContext(this IObject @this) => @this.Strategy.Transaction.Database.Context();
    }

    public static partial class TransactionExtensions
    {
        public static IDomainTransactionServices Context(this ITransaction @this) => ((IDomainTransactionServices)@this.Services);
    }

    public static partial class DatabaseExtensions
    {
        public static IDomainDatabaseServices Context(this IDatabase @this) => ((IDomainDatabaseServices)@this.Services);
    }
}
