// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace
{
    public static partial class ObjectExtensions
    {
        public static ISessionState SessionScope(this IStrategy @this) => @this.Context.Scope();

        public static WorkspaceState WorkspaceScope(this IStrategy @this) => @this.Context.ContextFactory.Scope();
    }

    public static partial class ContextExtensions
    {
        public static ISessionState Scope(this IContext @this) => ((ISessionState)@this.Lifecycle);
    }

    public static partial class WorkspaceExtensions
    {
        public static WorkspaceState Scope(this IContextFactory @this) => ((WorkspaceState)@this.Lifecycle);
    }
}
