// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Workspace
{
    public static partial class ObjectExtensions
    {
        public static ISessionStateState SessionState(this IStrategy @this) => @this.Session.State();

        public static WorkspaceStateState WorkspaceState(this IStrategy @this) => @this.Session.Workspace.State();
    }

    public static partial class SessionExtensions
    {
        public static ISessionStateState State(this ISession @this) => ((ISessionStateState)@this.StateLifecycle);
    }

    public static partial class WorkspaceExtensions
    {
        public static WorkspaceStateState State(this IWorkspace @this) => ((WorkspaceStateState)@this.StateLifecycle);
    }
}
