module.exports = {
  projects: [
    '<rootDir>/libs/data/core',
    '<rootDir>/libs/meta/core',
    '<rootDir>/libs/meta/generated',
    '<rootDir>/libs/meta/core',
    '<rootDir>/libs/protocol/core',
    '<rootDir>/libs/workspace/core',
    '<rootDir>/libs/workspace/memory',
    '<rootDir>/libs/domain/generated',
    '<rootDir>/libs/domain/base',
    '<rootDir>/libs/domain/custom',
    '<rootDir>/libs/data/core',
    '<rootDir>/libs/protocol/core',
    '<rootDir>/libs/workspace/core',
    '<rootDir>/libs/meta/base',
    '<rootDir>/libs/meta/apps',
    '<rootDir>/libs/domain/apps',
  ],
};
